### ISSUE TITLE
Poor Maze Generation Optimisation

### ISSUE THREAD

**Issue by JawwadC** [Kirimson/Jumazy#9] opened 2017-11-10 15:44 UTC
Generating the map can be very CPU intensive, which can make the game very slow to load and start up on lower end machines. This is likely due to the inefficiency of the loop statements involved with the random generation, as well as rendering the whole map in every single render loop.

**Steps to Reproduce: **
- Run the game on a low end machine
- Observe the time taken to generate the maze and move through it

**Comment by JawwadC** [comment] 2017-11-10 15:57
We can probably make a one time render or something like that.

**Comment by Kirimson** [comment] 2017-11-10 15:59
Duplicate of #5

**Comment by JawwadC** [comment] 2017-11-10 16:04
#5  @Kirimson @The-Wightman Im not sure how exavtly libgdx even does its rendering, or how this can be done.

**Closed as completed** 2017-11-10 16:50 UTC
Labels: enhancement, Core mechanic
